-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.card_holder
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.credit_card
(
    card character varying(20) NOT NULL,
    cardholder_id integer NOT NULL,
    PRIMARY KEY (card)
);

CREATE TABLE IF NOT EXISTS public.merchant_category
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.merchant
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    id_merchant_category integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaction
(
    id integer NOT NULL,
    date timestamp NOT NULL,
    amount double precision NOT NULL,
    card character varying(20) NOT NULL,
    id_merchant integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.credit_card
    ADD CONSTRAINT fk_card_holder FOREIGN KEY (cardholder_id)
    REFERENCES public.card_holder (id)
;


ALTER TABLE IF EXISTS public.merchant
    ADD CONSTRAINT fk_merchant_category FOREIGN KEY (id_merchant_category)
    REFERENCES public.merchant_category (id)
;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT fk_card FOREIGN KEY (card)
    REFERENCES public.credit_card (card) 
;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT fk_merchant FOREIGN KEY (id_merchant)
    REFERENCES public.merchant (id)
;

END;